"""Add sprint, task and task_links models

Revision ID: 49cb827fd037
Revises: 
Create Date: 2024-02-25 23:09:21.172196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cb827fd037'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('trivial', 'blocker', 'critical', 'major', 'minor', name='priority'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('planned_end_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_link',
    sa.Column('parent_task_id', sa.Integer(), nullable=False),
    sa.Column('child_task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('is_blocked_by', 'blocks', name='linkstatus'), nullable=False),
    sa.ForeignKeyConstraint(['child_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('parent_task_id', 'child_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_link')
    op.drop_table('task')
    op.drop_table('sprint')
    # ### end Alembic commands ###
