version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3.13.1
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"

  redis:
    image: redis:7.2.4
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
